# -*- coding: utf-8 -*-
"""nntestTask 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZ4RcYu8q8ajzjF1F8sxYzp7381SG24M
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

a= pd.read_csv("/content/nn_train.csv")

x_train=a.values[0:60000,1:1025]
y_train=a.values[0:60000,1025:1026]

x_test=a.values[60000:80000,1:1025]
y_test=a.values[60000:80000,1025:1026]


def sigmoid(z):
  g= 1/(1+np.exp(-z))
  return g

def compute_cost(x,y,w,b):
  m = x.shape[0]
  f_wb = sigmoid(np.matmul(x, w) + b)
  cost = (-1 / m) * (np.dot(y.T , np.log(f_wb)) + np.dot((1 - y).T, np.log(1 - f_wb)))
  cost = cost.item()
  return cost

def compute_gradient(x,y,w,b):
  m,n= x.shape
  dj_dw= np.zeros((n,1))
  dj_db=0
  f_wb=sigmoid(np.matmul(x,w)+b)
  dj_dw= np.matmul(x.T,(f_wb-y))
  dj_db=np.sum(f_wb-y)
  dj_dw=dj_dw/m
  dj_db=dj_db/m
  return dj_dw,dj_db

def gradient_descent(x,y,w,b,alpha,num_iterations):
   m,n=x.shape
   j_history=[]
   for i in range(num_iterations):
    dj_dw,dj_db= compute_gradient(x,y,w,b)
    w=w - alpha*dj_dw
    b=b-alpha*dj_db

    if i < num_iterations:
      j_history.append(compute_cost(x,y,w,b))

    if i%100 ==0:
      print(f"Iteration {i:4d}: Cost {j_history[-1]}   ")
   return w,b,j_history

w=np.zeros((1024,1))
b=0
w,b,j_history=gradient_descent(x_train,y_train,w,b,0.00000022,1000)

print(f'w={w}')
print(f'b={b}')

def compute_f1_score(y_true, y_pred):

    TP = np.sum((y_true == 1) & (y_pred == 1))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))

    precision = TP / (TP + FP) if TP + FP != 0 else 0
    recall = TP / (TP + FN) if TP + FN != 0 else 0

    f1 = 2 * (precision * recall) / (precision + recall) if precision + recall != 0 else 0
    return f1

y_predicted= sigmoid(np.matmul(x_test,w) + b)
for i in range(20000):
  if y_predicted[i]>=0.5:
    y_predicted[i]=1
  else:
    y_predicted[i]=0

f1 = compute_f1_score(y_test, y_predicted)
print(f'Test F1 Score: {f1:.4f}')

